spring:
  application:
    name: flowcopilot
  datasource:
    url: jdbc:postgresql://localhost:5432/flowcopilot
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: your-email
    password: your-password # 邮箱授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  type-aliases-package: aliang.flowcopilot.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: aliang.flowcopilot.typehandler

flowcopilot:
  llm:
    providers:
      deepseek:
        enabled: true
        api-key: sk-fc4fe40948fb4e668c3afff3026e5842
        base-url: https://api.deepseek.com
        model: deepseek-chat
        timeout: 60s
        log-requests: false
        log-responses: false
      zhipu:
        enabled: false
        api-key:
        base-url: https://open.bigmodel.cn/api/paas/v4
        model: glm-4.6
        timeout: 60s
        log-requests: false
        log-responses: false

document:
  storage:
    base-path: ./data/documents
