package aliang.flowcopilot.model.entity;

import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * A workflow deliverable generated by FlowCopilot.
 */
@Data
@Builder
public class Artifact {
    private String id;
    private String workflowInstanceId;
    private String type;
    private String title;
    private String content;
    private String metadata;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
